### ISSUE TITLE
Add package FreeSASA to not cripple BioPython

### ISSUE THREAD

**Issue by smkm** [iodide-project/pyodide#691] opened 2020-06-20 11:56 UTC
In protein bioinformatics, the solvent-accessible surface area of protein residues is a greatly important metric for protein analysis.
However, the most widely used libraries such as DSSP, NACCESS, and etc mostly have limitations in license usage or are close-sourced. 
Thus in the Bio.PDB subpackage of BioPython, while it did implement a wrapper to these programs, it did not include the programs that are supposed to run the backend of the wrapper. This, therefore, cripples the BioPython package in Pyodide significantly.
Luckily, an open-source version that calculates the solvent-accessible surface area called [FreeSASA](https://github.com/freesasa/freesasa-python) and its [PyPi](https://pypi.org/project/freesasa/) package can [complement the Bio.PDB](http://freesasa.github.io/python/intro.html#bio-pdb) package's problem, but it cannot be installed using micropip because there is not a pure python wheel, and must be installed using the tar.gz source file because it has C++ in the package.
Therefore I ask pyodide devs to implement this package for BioPython users to leverage at its maximum.

P.S. This project is a great leap forward in bioinformatics where its academically published servers were mostly server-side when it does not need to as static sites and serverless technologies are emerging. Keep up the great work!

**Comment by rth** [comment] 2020-06-24 19:16
Thanks for opening the issue. We don't have much maintainer resources to add new packages at the moment but FreeSASA developers or someone else would be very welcome to make a PR to add it to pyodide.

**Comment by smkm** [comment] 2020-06-27 06:54
The build has no big issues in #696 so I guess it can be merged and closed if tests succeed.

By the way, how does one wait for a package to be fully imported in the console before executing anything else? There should be a way for the console to wait until a package is loaded.

**Comment by rth** [comment] 2020-06-27 07:21
Thank you @smkm !

> By the way, how does one wait for a package to be fully imported in the console before executing anything else? There should be a way for the console to wait until a package is loaded.

I opened https://github.com/iodide-project/pyodide/issues/695 recently about it, the current situation can indeed be confusing.

**Comment by smkm** [comment] 2020-06-27 10:27
@rth By the way what is the reason a custom CDN is only used instead of hosted solutions like JSDelivr (at least for the js files)?

**Comment by rth** [comment] 2020-06-27 10:37
Resolved in https://github.com/iodide-project/pyodide/pull/696

> By the way what is the reason a custom CDN is only used instead of hosted solutions like JSDelivr (at least for the js files)?

Well the problem is not really hosting js files, it's hosting wasm files and associated data files which can be quite large. Their ability to serve files from Github releases could be worth investigating though.

**Closed by rth** 2020-06-27 10:37 UTC

**Comment by rth** [comment] 2020-06-27 10:44
> Their ability to serve files from Github releases could be worth investigating though.

No actually they serve files from github repos directly. The current issue with that is that we can't put build artifacts in a github repo since scipy build is larger that 100MB (cf https://github.com/iodide-project/pyodide/issues/240) and overall even putting scipy asize with one pyodide release taking up to 100MB we would reach the limit of 1GB per repo fairly quickly.

**Comment by smkm** [comment] 2020-06-27 15:55
Guess that means even if CDNs are willing to host for free it requires using their APIs to deploy the releases.
It could or could not be viable
Anyways thank you for pyodide, it will be an important part of a project of mine.
