### ISSUE TITLE
Share pyodide packages between webworkers and the main thread

### ISSUE THREAD

**Issue by oeway** [iodide-project/pyodide#242] opened 2018-11-06 19:32 UTC
Hi, thanks for the wonderful work. 

I am trying to use pyodide with webworkers, my question is that whether we can share packages between the main thread and webworkers? Ideally, I would like to load all the packages in the main thread `pyodide.loadPackage('numpy'))` and get a reusable object which can be sent to the webworker with `postMessage`. 

All the major browsers have supported sending WASM modules with `postMessage` ( https://www.chromestatus.com/feature/6012085880225792 ), but I am not sure that how can we access the WASM modules with pyodide and reuse them in the webworker.

Could you please give some hint on how this could be done?

**Comment by mdboom** [comment] 2018-11-06 21:48
I don't think you can share them in this way.  `loadPackage` installs files in the "virtual filesystem", which I don't think is shared between webworkers and the main thread.  However, I'm a bit out of my depth of knowledge here.  Maybe try asking the more general question of sharing the filesystem between webworkers and the main thread in the emscripten issue tracker...?

**Comment by oeway** [comment] 2018-11-08 12:57
Thanks. I see, so I just need to share the `.js` and `.data` file to the web work and it would be possible to reuse the package. I did a bit research on the file system in Emscripten, the file system would be `MEMFS` by default, which means all the files will stay in the memory. Is that the case for pyodide? 

Would it be possible to switch to `IDBFS` which uses the IndexedDB as a backend? I can see a few reasons to use that, for example we can persist the virtual file system without downloading everytime, and also since IndexedDB will stay on the disk, it will reduce the usage of memory.

Besides sharing the package files ( `.js` and `.data` ), would it make sense to share the loaded wasm modules between different workers? I would expect that will further reduce the requirement of memory, since modules could be reused.

**Comment by mdboom** [comment] 2018-11-08 13:58
> Thanks. I see, so I just need to share the .js and .data file to the web work and it would be possible to reuse the package.

Not really, since I don't think the MEMFS is shared between the main thread and the web workers.  You would duplicate memory usage there.

> Would it be possible to switch to IDBFS which uses the IndexedDB as a backend?

I would be interesting to experiment with that, but I haven't tried it.  

> persist the virtual file system without downloading everytime

As it stands, the files are cached anyway, so they aren't downloaded every time.  They are unpacked into the virtual filesystem, of course, but only the files that actually get accessed.

Persistence may actually be an anti-feature -- if files are overwritten, for example, behavior could change on subsequent loads of the page.  Also, if the user comes to rely on the persistence, they may run into issues when the browser, at its discretion, evicts files.  I suppose if we can force the filesystem to be read-only, we'll avoid many of these issues.

> Besides sharing the package files ( .js and .data ), would it make sense to share the loaded wasm modules between different workers?

It probably would.  My understanding is that compiled WebAssembly modules can be passed as messages between web workers.

**Comment by oeway** [comment] 2018-11-08 15:33
For MEMFS, I think right now emscripten uses TypedArrays to store files, if [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) can be used, then maybe it's possible to share the file system betwen workers and main thread.

I am  a bit surprised that persistence would be considered as an anti-feature, since that's how native Python modules works. Can't we have something like `pyodide.installPackage` to install packages into the `site-packages` folder in the virtual file system? Since dependencies are handled during installation, the subsequent loads of the page should not break. No? 

Ideally, I think it would be great to maintain that `site-packages` folder stored in IndexedDB, and the user can choose to run `pyodide.upgradePackage`. And when `pyodide.loadPackage` is called, it will load to MEMFS from IndexedDB, or directly use the packages with IDBFS.

It would be a shame that the pyodide can only work with (good) internet connected. For a long term, I think it's important to support offline-first Progressive Web Apps which can run even without internet.

**Comment by mdboom** [comment] 2018-11-08 15:43
My point with persistence as an anti-feature is that if the filesystem gets in a broken state, we'd need some way to correct for that.  As it stands now, since you're getting basically a fresh install every time you visit a page, the user experience is the same every time you or any other person visits.  This is really good for reproducibility.  Imagine a situation where a user corrected a bug by installing an updated version of a package in their own filesystem, and then when sharing the notebook sees it still broken.  That seems like a hard to understand, debug and correct situation.

> It would be a shame that the pyodide can only work with (good) internet connected. 

The caching in the browser already comes into play, so pyodide already works when disconnected -- assuming it's served correctly, which it may not be at the moment.  But I think caching on that level and starting with a clean state each time is a cleaner model in general.

Don't get me wrong -- there might be some benefit to using a persistent filesystem and I would encourage experimenting with it as a potential advanced feature, but I think it might create more problems around reproducibility than it solves.

Note that tools like binder also start with a clean slate each time a notebook is loaded, and requirements installation is effectively done on each startup.

**Comment by oeway** [comment] 2018-11-08 16:35
Right, then I think the choice should leave to the app developer if persistence is supported: I mean, you can always add a few lines to clean up previous installations if you want to make sure you start from a good state.

Just to make it more clear about the need of persistence, I understand that it make sense for a notebook environment to reload every time. However, at least for the app I am trying to develop, we weight persistence differently. Different from a notebook environment where the user can directly code in the browser, we run fixed python files with pyodide, and we can easily run some test code to check if everything works and then decide to reinstall packages or not. For us, and also potentially for other apps (especially on mobile devices), what we really want is the small memory footprint, fast page loading and offline access. 

When I say offline access, I mean start the application without internet (using [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)).

> Don't get me wrong -- there might be some benefit to using a persistent filesystem and I would encourage experimenting with it as a potential advanced feature, but I think it might create more problems around reproducibility than it solves.
Agreed.

**Comment by rth** [comment] 2020-05-08 20:40
Given that this discussion is from 2018 and there is now [a documentation section on using web-workers with pyodide](https://pyodide.readthedocs.io/en/latest/using_pyodide_from_webworker.html) closing as outdated.  Please comment if it's not the case.

**Closed by rth** 2020-05-08 20:40 UTC
Labels: WASM
