### ISSUE TITLE
Unable to build on Ubuntu 18.04 | assertion fail in numpy

### ISSUE THREAD

**Issue by mishranant** [iodide-project/pyodide#329] opened 2019-02-27 13:39 UTC
Executing `make` command in root gives off the following trace, ending up in an assertion error. I am unable to fix this myself. Google search results suggest to upgrade numpy and scipy, but that does not help. Here is the log:
```
building extension "scipy.interpolate._interpolate" sources
building extension "scipy.io.matlab.streams" sources
building extension "scipy.io.matlab.mio_utils" sources
building extension "scipy.io.matlab.mio5_utils" sources
building extension "scipy.linalg._fblas" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg' to include_dirs.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/_fblas-f2pywrappers.f' to sources.
building extension "scipy.linalg._flapack" sources
f2py options: []
f2py: build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
Reading fortran codes...
	Reading file 'build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf' (format:free)
Traceback (most recent call last):
File "setup.py", line 265, in <module>
    setup_package()
  File "setup.py", line 262, in setup_package
    setup(**metadata)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/command/install.py", line 60, in run
    r = old_install.run(self)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 325, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 542, in f2py_sources
    + ['--build-dir', target_dir, source])
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode
    dowithline(finalline)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline
    analyzeline(m, pat[1], line)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1098, in analyzeline
    last_name = updatevars(typespec, selector, attr, edecl)
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1542, in updatevars
    attrspec = [x.strip() for x in markoutercomma(attrspec).split('@,@')]
  File "/home/anant/testpy/pyodide/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'intent(in))', 'intent(in))')
Traceback (most recent call last):
  File "/home/anant/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anant/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anant/testpy/pyodide/pyodide_build/__main__.py", line 30, in <module>
    main()
  File "/home/anant/testpy/pyodide/pyodide_build/__main__.py", line 24, in main
    args.func(args)
  File "/home/anant/testpy/pyodide/pyodide_build/buildall.py", line 93, in main
    build_packages(packagesdir, outputdir, args)
  File "/home/anant/testpy/pyodide/pyodide_build/buildall.py", line 50, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/home/anant/testpy/pyodide/pyodide_build/buildall.py", line 24, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/home/anant/testpy/pyodide/pyodide_build/buildpkg.py", line 162, in build_package
    compile(path, srcpath, pkg, args)
  File "/home/anant/testpy/pyodide/pyodide_build/buildpkg.py", line 100, in compile
    '--target', args.target], env=env, check=True)
  File "/home/anant/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/anant/testpy/pyodide/cpython/build/3.7.0/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' -I../../../../CLAPACK/CLAPACK-WA/INCLUDE -Wno-implicit-function-declaration', '--ldflags', '-O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 ', '--host', '/home/anant/testpy/pyodide/cpython/build/3.7.0/host', '--target', '/home/anant/testpy/pyodide/cpython/installs/python-3.7.0']' returned non-zero exit status 1.
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/anant/testpy/pyodide/packages'
Makefile:225: recipe for target 'build/packages.json' failed
make: *** [build/packages.json] Error 2
```

**Comment by mdboom** [comment] 2019-02-27 19:44
I think the actual output from `f2py` is getting swallowed here, so we can't see the root cause of the error.

Have you had success with the docker image, which should give a consistent dev environment and hopefully work around anything that's different about your machine?

**Comment by msabramo** [comment] 2019-08-15 07:20
Hmmm - I just got this same error I think and I got it while using the Docker image.

**Comment by mdboom** [comment] 2019-08-15 11:48
This is a puzzler.  I wonder if somehow `build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf` is corrupted or only partially written?

**Comment by msabramo** [comment] 2019-08-15 13:05
```
root@8627945dd8f5:/src# ls -l packages/scipy/build/scipy-0.17.1/build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
-rw-r--r-- 1 root root 282599 Aug 15 07:13 packages/scipy/build/scipy-0.17.1/build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
root@8627945dd8f5:/src# file packages/scipy/build/scipy-0.17.1/build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
packages/scipy/build/scipy-0.17.1/build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf: ASCII text
root@8627945dd8f5:/src# head packages/scipy/build/scipy-0.17.1/build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
!%f90 -*- f90 -*-
! Signatures for f2py wrappers of FORTRAN LAPACK functions.
!
! Author: Pearu Peterson
! Created: Jan-Feb 2002
! $Revision$ $Date$
!
! Additions by Travis Oliphant, Tiziano Zito, Collin RM Stocks, Fabian Pedregosa
!              Skipper Seabold
!
```

**Comment by mdboom** [comment] 2019-08-15 13:08
Yeah -- that doesn't look like it has any "real" content.  Does deleting `packages/scipy/build` and running `make` again (at the top-level) help?

**Comment by msabramo** [comment] 2019-08-15 13:17
Well,

```
root@8627945dd8f5:/src# rm packages/scipy/build/scipy-0.17.1/build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
root@8627945dd8f5:/src# make
```

didn't help. Now I'll try your idea of nuking the whole scipy build...

**Comment by msabramo** [comment] 2019-08-15 13:33
Hmmm that didn't help either.

```
root@8627945dd8f5:/src# rm -rf packages/scipy/build/scipy-0.17.1
root@8627945dd8f5:/src# make
...
	Wrote C/API module "_fblas" to file "build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/_fblasmodule.c"
	Fortran 77 wrappers are saved to "build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/_fblas-f2pywrappers.f"
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg' to include_dirs.
creating build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build
creating build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7
creating build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy
creating build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg
copying /src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/src/fortranobject.c -> build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg
copying /src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/src/fortranobject.h -> build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/_fblas-f2pywrappers.f' to sources.
building extension "scipy.linalg._flapack" sources
from_template:> build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
Including file scipy/linalg/flapack_user.pyf.src
Mismatch in number of replacements (base <prefix2=s,d>) for <__l1=S/D>. Ignoring.
Mismatch in number of replacements (base <prefix2c=c,z>) for <__l1=C/Z>. Ignoring.
Mismatch in number of replacements (base <prefix2=s,d>) for <__l1=S/D>. Ignoring.
Mismatch in number of replacements (base <prefix2=s,d>) for <__l1=S/D>. Ignoring.
Mismatch in number of replacements (base <prefix2c=c,z>) for <__l1=C/Z>. Ignoring.
Mismatch in number of replacements (base <prefix2c=c,z>) for <__l1=C/Z>. Ignoring.
f2py options: []
f2py: build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
Reading fortran codes...
	Reading file 'build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf' (format:free)
Traceback (most recent call last):
  File "setup.py", line 265, in <module>
    setup_package()
  File "setup.py", line 262, in setup_package
    setup(**metadata)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/command/install.py", line 60, in run
    r = old_install.run(self)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 325, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/distutils/command/build_src.py", line 542, in f2py_sources
    + ['--build-dir', target_dir, source])
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 501, in readfortrancode
    dowithline(finalline)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 796, in crackline
    analyzeline(m, pat[1], line)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 1098, in analyzeline
    last_name = updatevars(typespec, selector, attr, edecl)
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 1542, in updatevars
    attrspec = [x.strip() for x in markoutercomma(attrspec).split('@,@')]
  File "/src/cpython/build/3.7.0/host/lib/python3.7/site-packages/numpy-1.16.2-py3.7-linux-x86_64.egg/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'intent(in))', 'intent(in))')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 91, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 48, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 21, in build_package
    build_package(req, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 22, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 210, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 122, in compile
    '--target', args.target], env=env, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/src/cpython/build/3.7.0/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' -I../../../../CLAPACK/CLAPACK-WA/INCLUDE -Wno-implicit-function-declaration', '--ldflags', '-O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 ', '--host', '/src/cpython/build/3.7.0/host', '--target', '/src/cpython/installs/python-3.7.0']' returned non-zero exit status 1.
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/src/packages'
Makefile:243: recipe for target 'build/packages.json' failed
make: *** [build/packages.json] Error 2
```

**Comment by msabramo** [comment] 2019-08-15 13:38
Here's the line of code where the assertion fails:

![Screen Shot 2019-08-15 at 6 36 42 AM](https://user-images.githubusercontent.com/305268/63098206-3710fa00-bf27-11e9-90b0-b35092a85a15.png)

**Comment by mdboom** [comment] 2019-08-15 14:02
Hmm...  I'm a bit stumped.  You said this was in the Docker image (so unlikely another version of Numpy/f2c getting picked up that is somehow interfering with changed behavior).  You could try printing the `line` here to get a sense of why it's failing, I guess...

**Comment by msabramo** [comment] 2019-08-15 15:16
Hmmm, I tried `rm -rf cpython/build/3.7.0` and rebuilt cpython but now when I do `make` from the top-level, I get this:

```
root@8627945dd8f5:/src/packages# make
...
Traceback (most recent call last):
  File "setup.py", line 265, in <module>
    setup_package()
  File "setup.py", line 253, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/pyodide_build/__main__.py", line 32, in <module>
    main()
  File "/src/pyodide_build/__main__.py", line 26, in main
    args.func(args)
  File "/src/pyodide_build/buildall.py", line 91, in main
    build_packages(packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 48, in build_packages
    build_package(pkgname, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 21, in build_package
    build_package(req, dependencies, packagesdir, outputdir, args)
  File "/src/pyodide_build/buildall.py", line 22, in build_package
    buildpkg.build_package(packagesdir / pkgname / 'meta.yaml', args)
  File "/src/pyodide_build/buildpkg.py", line 210, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide_build/buildpkg.py", line 122, in compile
    '--target', args.target], env=env, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/src/cpython/build/3.7.0/host/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', ' -I../../../../CLAPACK/CLAPACK-WA/INCLUDE -Wno-implicit-function-declaration', '--ldflags', '-O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 ', '--host', '/src/cpython/build/3.7.0/host', '--target', '/src/cpython/installs/python-3.7.0']' returned non-zero exit status 1.
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by mdboom** [comment] 2019-08-15 15:37
Maybe force a rebuild of the numpy package also?  (`rm -rf packages/numpy/build`)

**Comment by msabramo** [comment] 2019-08-15 22:00
I did:

```
rm -rf numpy/build
make
```

and everything looks good:

```
$ make
...
running install_scripts
Remember to build the main file with  -s FORCE_FILESYSTEM=1  so that it includes support for loading this file package
converting to ArrayBuffer
compressing package of size 37226622
compressed package into 15558802
compressed in 1812 ms
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
make[1]: Leaving directory '/src/packages'
cp src/test.html build/test.html
cp src/webworker.js build/webworker.js
sed -i -e 's#{{DEPLOY}}#https://pyodide.cdn.iodide.io/#g' build/webworker.js
cp src/webworker.js build/webworker_dev.js
sed -i -e "s#{{DEPLOY}}##g" build/webworker_dev.js
sed -i -e "s#pyodide.js#pyodide_dev.js#g" build/webworker_dev.js
```

**Comment by mdboom** [comment] 2019-08-16 11:40
Apologies for the hard time.  We definitely need to make the build more robust to these sorts of things.

**Comment by rth** [comment] 2021-02-08 20:47
There have been a lot of changes in the build setup since 2019  so I'm closing this. If you still experience issues with the build please open a new issue.

**Closed by rth** 2021-02-08 20:47 UTC

**Comment by rth** [comment] 2021-02-25 22:16
I run into this this recently, and this indeed happens when building scipy 0.17.1 with a version of numpy newer than 1.17.0. The fix is in https://github.com/scipy/scipy/pull/8530 which will be added as a patch in https://github.com/iodide-project/pyodide/pull/887.

Though the fact that it happened before in this issue is likely a symptom that an incorrect/system version of numpy was imported at build time, instead of the one that we built.
