### ISSUE TITLE
Some chrome tests timing out fetching resources

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#138] opened 2018-09-05 13:29 UTC
Following the merge of #95, though it's not clear how that's related.

https://circleci.com/gh/iodide-project/pyodide/408?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by rth** [comment] 2018-09-05 13:42
Would you be able to restart that build please to see if it's reproducible?

This seems to be happening in the HTTP server fixture,
```
/usr/local/lib/python3.6/http/client.py:258: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <socket.SocketIO object at 0x7f518cf803c8>
b = <memory at 0x7f518d2ed648>

    def readinto(self, b):
[..]
        while True:
            try:
>               return self._sock.recv_into(b)
E               ConnectionResetError: [Errno 104] Connection reset by peer

/usr/local/lib/python3.6/socket.py:586: ConnectionResetError
```

**Comment by mdboom** [comment] 2018-09-05 13:52
Actually, I'm mistaken.  This was after the merge of #136, but then after merging #95 it's working again.  So it seems to be non-deterministic.  Let's hope it was just a passing slowness in Circle-CI and not something on our end.

**Comment by rth** [comment] 2018-09-06 09:07
That is strange, not sure why it started happening. Latest commit on master passed...

**Comment by rth** [comment] 2020-05-08 20:37
Closing as no longer relevant.

**Closed by rth** 2020-05-08 20:37 UTC
