### ISSUE TITLE
matplotlib successfully imports but pandas plot method results in exception: ImportError, matplotlib is required for plotting

### ISSUE THREAD

**Issue by unhott** [iodide-project/pyodide#805] opened 2020-11-23 04:50 UTC
I'm following docs as best I can on a pretty simple HTML example so far. I eventually realized I needed to call runPythonAsync instead of runPython in order to get pandas working, and was able to refactor that successfully. But this next part is confusing me. 

I have a code tag that has this code : 
```py
import pandas as pd
import numpy as np
import matplotlib #added for testing - confusion results
df = pd.Series([i for i in range(100)], index=pd.date_range('1/1/2000', periods=100)).cumsum()
df.plot()
```
I ran it and got a big traceback error resulting in matplotlib being required. I thought maybe it's a quirk about fetching the dependencies, so I then explicitly imported matplotlib. However, I still get this: 

Full trace
```
matplotlib already loaded from default channel pyodide.js:104:15
numpy already loaded from default channel pyodide.js:104:15
pandas already loaded from default channel pyodide.js:104:15
Python exception: pyodide.asm.js:8:56405
Traceback (most recent call last): pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pyodide.py", line 45, in eval_code pyodide.asm.js:8:56405
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns) pyodide.asm.js:8:56405
  File "<eval>", line 5, in <module> pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 2741, in __call__ pyodide.asm.js:8:56405
    **kwds) pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 2002, in plot_series pyodide.asm.js:8:56405
    **kwds) pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 1802, in _plot pyodide.asm.js:8:56405
    plot_obj = klass(data, subplots=subplots, ax=ax, kind=kind, **kwds) pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 939, in __init__ pyodide.asm.js:8:56405
    MPLPlot.__init__(self, data, **kwargs) pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 107, in __init__ pyodide.asm.js:8:56405
    _raise_if_no_mpl() pyodide.asm.js:8:56405
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 57, in _raise_if_no_mpl pyodide.asm.js:8:56405
    raise ImportError("matplotlib is required for plotting.") pyodide.asm.js:8:56405
ImportError: matplotlib is required for plotting. pyodide.asm.js:8:56405
<empty string> pyodide.asm.js:8:56405
Uncaught (in promise) Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 45, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 5, in <module>
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 2741, in __call__
    **kwds)
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 2002, in plot_series
    **kwds)
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 1802, in _plot
    plot_obj = klass(data, subplots=subplots, ax=ax, kind=kind, **kwds)
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 939, in __init__
    MPLPlot.__init__(self, data, **kwargs)
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 107, in __init__
    _raise_if_no_mpl()
  File "/lib/python3.7/site-packages/pandas/plotting/_core.py", line 57, in _raise_if_no_mpl
    raise ImportError("matplotlib is required for plotting.")
ImportError: matplotlib is required for plotting.
    _hiwire_throw_error https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.asm.js:8
    __runPython https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.asm.js:8
    _runPythonInternal https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.asm.js:8
    internal https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.asm.js:8
    runInternal https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.asm.js:8
    promise callback*_runpython_init_js/Module.runPythonAsync https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.asm.js:8
    runAllCodeBlocks http://localhost:8000/9/:150
    runAllCodeBlocks http://localhost:8000/9/:146
    promise callback*runAllCodeBlocks http://localhost:8000/9/:145
    onclick http://localhost:8000/9/:1
```

**Comment by rth** [comment] 2020-11-30 21:33
I can indeed reproduce this with pyodide 0.15.0 but this error no longer happens with pyodide 0.16.0 likely because because it was fixed in newer pandas relased. So this should be fixed in the next pyodide release.

**Comment by rth** [comment] 2021-02-08 21:02
Closing as resolved.

**Closed by rth** 2021-02-08 21:02 UTC
