### ISSUE TITLE
how to restart pyodide or clear variables?

### ISSUE THREAD

**Issue by akirakotsugai** [iodide-project/pyodide#881] opened 2020-12-17 10:17 UTC
I would like to have a fresh and clean workspace before calling a "runPython", and clear the variable assignments from a previous "runPython".

Is that possible?

**Comment by rth** [comment] 2020-12-17 11:27
This is a frequently asked feature that is not implemented yet. Closing as a duplicate of https://github.com/iodide-project/pyodide/issues/703 , don't hesitate to comment in that issue.

**Closed by rth** 2020-12-17 11:27 UTC
