### ISSUE TITLE
Create tag for commit a4fad9b

### ISSUE THREAD

**Issue by johnwason** [iodide-project/pyodide#1327] opened 2021-03-13 03:45 UTC
Commit a4fad9b appears to be the last commit before updating to emscipten 2.x. The change has some pretty significant compatibility issues, so it would be useful to have a tag for the last emscripten 1.x version for reference.

**Comment by rth** [comment] 2021-03-13 12:05
I understand that it would be useful. The issue is that there have been lots of breaking changes since the last release as part of type conversion re-design by @hoodmane  + async support, so we would need a good migration guide. And that commit is pretty much in the middle of those changes.

So,
 - we can't release it as v0.16.2 because it's clearly not minor
 - we can't release it as v0.17.0 because then we would have to make a proper migration guide and keep changelog which would be complicated with half integrated type conversions changes. Also it's strange to make a major release of 1 month old code.


We could probably make a v0.17.dev0-a4fad9b tag, and mention it the changelog under v0.17.0 as intermediary version that could be used for the migration process.

Alternatively addressing the issues you mention in https://github.com/emscripten-core/emscripten/issues/13607 on master would be good in any case.

**Comment by johnwason** [comment] 2021-03-13 23:09
The dev tag should be fine.

I am trying to merge in the changes from master in the type conversions, and am getting this error:

```
exception thrown: TypeError: Module.handle_js_error is not a function,_hiwire_init@http://192.168.1.133:8000/build/pyodide.asm.js:8:178664
@http://192.168.1.133:8000/build/pyodide.asm.wasm:wasm-function[539]:0x46dc8e
pyodide/Module._main@http://192.168.1.133:8000/build/pyodide.asm.js:8:8557197
callMain@http://192.168.1.133:8000/build/pyodide.asm.js:8:9854204
doRun@http://192.168.1.133:8000/build/pyodide.asm.js:8:9854799
run@http://192.168.1.133:8000/build/pyodide.asm.js:8:9854963
runCaller@http://192.168.1.133:8000/build/pyodide.asm.js:8:9853863
removeRunDependency@http://192.168.1.133:8000/build/pyodide.asm.js:8:160841
receiveInstance@http://192.168.1.133:8000/build/pyodide.asm.js:8:162741
receiveInstantiatedSource@http://192.168.1.133:8000/build/pyodide.asm.js:8:162857
promise callback*instantiateAsync/<@http://192.168.1.133:8000/build/pyodide.asm.js:8:163415
promise callback*instantiateAsync@http://192.168.1.133:8000/build/pyodide.asm.js:8:163318
createWasm@http://192.168.1.133:8000/build/pyodide.asm.js:8:163868
pyodide/Module.asm@http://192.168.1.133:8000/build/pyodide.asm.js:8:164125
pyodide@http://192.168.1.133:8000/build/pyodide.asm.js:8:971480
globalThis.languagePluginLoader<@http://192.168.1.133:8000/build/pyodide.js:666:24
async*@http://192.168.1.133:8000/build/pyodide.js:701:3
```

The function is defined in error_handling.c, and error_handling.o is included in the main package. Is there anything obvious that would be causing this?

**Comment by hoodmane** [comment] 2021-03-13 23:12
Can you give a link to the repo? Maybe `error_handling_init` isn't getting called?

**Comment by johnwason** [comment] 2021-03-13 23:15
Here is my current progress:

https://github.com/johnwason/pyodide/tree/merge_master_conversions

It is likely `error_handling_init` isn't being called. I didn't see where it is called in master.

**Comment by hoodmane** [comment] 2021-03-13 23:22
Swap line 111 and line 112 in main:
https://github.com/johnwason/pyodide/blob/e7d38561a618d427998f774c560aba2b791dba2c/src/core/main.c#L111
This initialization order mistake is masking some other problem. After you swap, recompile and you should get a better error message. Also, I'd recommend compiling with `EXTRA_CFLAGS='-D DEBUG_F`.

**Comment by hoodmane** [comment] 2021-03-13 23:24
In particular, there is probably some dumb mistake in `hiwire_init`.

**Comment by johnwason** [comment] 2021-03-13 23:27
```
exception thrown: TypeError: Module.hiwire.new_value is not a function,_error_handling_init_js/Module.handle_js_error@http://192.168.1.133:8000/build/pyodide.asm.js:8:165916
_hiwire_init@http://192.168.1.133:8000/build/pyodide.asm.js:8:178664
@http://192.168.1.133:8000/build/pyodide.asm.wasm:wasm-function[539]:0x46dcf4
pyodide/Module._main@http://192.168.1.133:8000/build/pyodide.asm.js:8:8557197
callMain@http://192.168.1.133:8000/build/pyodide.asm.js:8:9854204
doRun@http://192.168.1.133:8000/build/pyodide.asm.js:8:9854799
run@http://192.168.1.133:8000/build/pyodide.asm.js:8:9854963
runCaller@http://192.168.1.133:8000/build/pyodide.asm.js:8:9853863
removeRunDependency@http://192.168.1.133:8000/build/pyodide.asm.js:8:160841
receiveInstance@http://192.168.1.133:8000/build/pyodide.asm.js:8:162741
receiveInstantiatedSource@http://192.168.1.133:8000/build/pyodide.asm.js:8:162857
```

**Comment by hoodmane** [comment] 2021-03-13 23:32
That seems like it should narrow it down to some line between 
https://github.com/johnwason/pyodide/blob/e7d38561a618d427998f774c560aba2b791dba2c/src/core/hiwire.c#L24
and 
https://github.com/johnwason/pyodide/blob/e7d38561a618d427998f774c560aba2b791dba2c/src/core/hiwire.c#L49

Can you add a `console.log("Made it this far?");` to L48 and see if it prints?

**Comment by hoodmane** [comment] 2021-03-13 23:36
I think if you compile with `EXTRA_CFLAGS="-D DEBUG_F"` it should give a much better error message though. In that case, `LOG_EM_JS_ERROR` should give a very clear message:
https://github.com/johnwason/pyodide/blob/e7d38561a618d427998f774c560aba2b791dba2c/src/core/error_handling.h#L66
this happens before it makes any attempt to touche `hiwire.new_value`.

**Comment by johnwason** [comment] 2021-03-13 23:53
```
EM_JS raised exception on line 114 in func hiwire_init pyodide.asm.js:8:184258
    _hiwire_init http://192.168.1.133:8000/build/pyodide.asm.js:8
    <anonymous> http://192.168.1.133:8000/build/pyodide.asm.wasm:4650552
    _main http://192.168.1.133:8000/build/pyodide.asm.js:8
    callMain http://192.168.1.133:8000/build/pyodide.asm.js:8
    doRun http://192.168.1.133:8000/build/pyodide.asm.js:8
    run http://192.168.1.133:8000/build/pyodide.asm.js:8
    runCaller http://192.168.1.133:8000/build/pyodide.asm.js:8
    removeRunDependency http://192.168.1.133:8000/build/pyodide.asm.js:8
    receiveInstance http://192.168.1.133:8000/build/pyodide.asm.js:8
    receiveInstantiatedSource http://192.168.1.133:8000/build/pyodide.asm.js:8
Error was: ReferenceError: _Js_undefined is not defined
    _hiwire_init http://192.168.1.133:8000/build/pyodide.asm.js:8
    _main http://192.168.1.133:8000/build/pyodide.asm.js:8
    callMain http://192.168.1.133:8000/build/pyodide.asm.js:8
    doRun http://192.168.1.133:8000/build/pyodide.asm.js:8
    run http://192.168.1.133:8000/build/pyodide.asm.js:8
    runCaller http://192.168.1.133:8000/build/pyodide.asm.js:8
    removeRunDependency http://192.168.1.133:8000/build/pyodide.asm.js:8
    receiveInstance http://192.168.1.133:8000/build/pyodide.asm.js:8
    receiveInstantiatedSource http://192.168.1.133:8000/build/pyodide.asm.js:8
pyodide.asm.js:8:184330
    _hiwire_init http://192.168.1.133:8000/build/pyodide.asm.js:8
    <anonymous> http://192.168.1.133:8000/build/pyodide.asm.wasm:4650552
    _main http://192.168.1.133:8000/build/pyodide.asm.js:8
    callMain http://192.168.1.133:8000/build/pyodide.asm.js:8
    doRun http://192.168.1.133:8000/build/pyodide.asm.js:8
    run http://192.168.1.133:8000/build/pyodide.asm.js:8
    runCaller http://192.168.1.133:8000/build/pyodide.asm.js:8
    removeRunDependency http://192.168.1.133:8000/build/pyodide.asm.js:8
    receiveInstance http://192.168.1.133:8000/build/pyodide.asm.js:8
    receiveInstantiatedSource http://192.168.1.133:8000/build/pyodide.asm.js:8
```

**Comment by hoodmane** [comment] 2021-03-14 00:01
Okay that's pretty specific.

**Comment by hoodmane** [comment] 2021-03-14 00:02
What if you say `Module._Js_undefined`? Does it work then?
```js
  Module.hiwire.UNDEFINED = HEAP8[Module._Js_undefined];
  Module.hiwire.JSNULL = HEAP8[Module._Js_null];
  Module.hiwire.TRUE = HEAP8[Module._Js_true];
  Module.hiwire.FALSE = HEAP8[Module._Js_false];
```

**Comment by johnwason** [comment] 2021-03-14 00:09
Where would I put that? pyodide.js gets stuck and never finishes so I don't think I can access Module.

**Comment by johnwason** [comment] 2021-03-14 00:35
Ok I see where to change that in hiwire.c. I get "Python Initialization Complete", and then the code gets stuck in an infinite loop on `await languagePluginLoader'.

**Comment by hoodmane** [comment] 2021-03-14 00:38
Can you access the `pyodide` object? Does it have a `runPythonSimple` field on it? Try:
`Module.runPythonSimple("print('not completely broken??')")`

**Comment by johnwason** [comment] 2021-03-14 00:40
No, it seems to be crashing the browser in the async loop. I'll revert back to my previous version and work on compiling against master sometime in the future.

**Comment by rth** [comment] 2021-03-19 13:07
> v0.17.dev0-a4fad9b tag

Actually I think we might as well make a v0.17.0a1 before the emscripten upstream migration, and maybe make another v0.17.0a2 for current master, to make it easier for users to test it without relying on the dev version (which can break more easily as updated on each commit and is not well cached by the CDN).

**Comment by rth** [comment] 2021-03-19 13:07
I'll do that unless there are objections.

**Comment by rth** [comment] 2021-03-22 08:30
Resolved in https://github.com/iodide-project/pyodide/releases/tag/0.17.0a1

**Closed by rth** 2021-03-22 08:30 UTC
