### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by karray** [iodide-project/pyodide#768] opened 2020-10-14 18:08 UTC
I'm just curious why I can't call some js functions like `alert` or `fetch`.
Every time I call `alert` I get `TypeError: Illegal invocation` without any further Information and call stack.

```python
import js

js.alert('Hi!')
```

If I assign `window` to the `pyodide.globals` object from js, `window.alert` will work form python
```js
pyodide.globals.window = window
```

Any ideas?

**Comment by rth** [comment] 2020-10-14 19:24
In Firefox the error message is a bit more explicit when calling `js.alert`,
```
Uncaught (in promise) TypeError: 'alert' called on an object that does not implement interface Window.
    _hiwire_call https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    __runPython https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    _runPythonInternal https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    runPython https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.js:8
    <anonymous> http://localhost:8000/:15
    promise callback* http://localhost:8000/:14
pyodide.asm.js:8:30960
``` 

`alert` JS function seems to be an alias to the [`window.alert`](https://www.w3schools.com/jsref/met_win_alert.asp) method. For instance,
```py
from js import window
window.alert('test')
```
works as expected. 

Same thing with `fetch`: use
```py
from js import window
window.fetch(...)
```
instead. 

Someone would need to investigate why the initial aliasing of these functions to `window` methods doesn't currently work with pyodide.

**Comment by hoodmane** [comment] 2020-12-31 06:32
This a duplicate of #461.

**Closed** 2020-12-31 06:35 UTC
