### ISSUE TITLE
Pyodide demo not loading

### ISSUE THREAD

**Issue by danielgwilson** [iodide-project/pyodide#311] opened 2019-01-31 00:12 UTC
Demo link appears to be broken at the moment—it shows a Not Found error.

https://extremely-alpha.iodide.io/pyodide-demo/python.html

Tested on OSX
* Chrome
* Safari

**Comment by rth** [comment] 2019-01-31 07:01
Thanks for the report. I can confirm. Related to https://github.com/iodide-project/pyodide/issues/294

Also https://iodide.io/pyodide-demo/python.html not longer serves files from https://github.com/iodide-project/pyodide-demo but instead redirects to a missing location on https://extremely-alpha.iodide.io/,
(and there seem to be a double redirect HTTPS -> HTTP -> HTTPS for some reason) 

```
wget https://iodide.io/pyodide-demo/python.html
--2019-01-31 07:53:50--  https://iodide.io/pyodide-demo/python.html
Resolving iodide.io... 216.239.32.21, 216.239.34.21, 216.239.36.21, ...
Connecting to iodide.io|216.239.32.21|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://extremely-alpha.iodide.io/pyodide-demo/python.html [following]
--2019-01-31 07:53:50--  http://extremely-alpha.iodide.io/pyodide-demo/python.html
Resolving extremely-alpha.iodide.io... 34.206.36.121, 34.204.22.7, 34.206.253.53, ...
Connecting to extremely-alpha.iodide.io|34.206.36.121|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://extremely-alpha.iodide.io/pyodide-demo/python.html [following]
--2019-01-31 07:53:50--  https://extremely-alpha.iodide.io/pyodide-demo/python.html
Connecting to extremely-alpha.iodide.io|34.206.36.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-31 07:53:51 ERROR 404: Not Found.
```

**Comment by oeway** [comment] 2019-02-21 16:19
Maybe related to this issue, I got some problem when I try to deploy the latest pyodide release (v0.8.0) to github pages.

When I open the served version of `python.html`, It tries to access a file `http://extremely-alpha.iodide.io/dist/iodide.pyodide-20180623.js` through `http` which is blocked by the browser because `Mixed Content`.

If I switch to `http`, then I got another error `Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://iodide-project.github.io/dist/".` This is because when the browser try to fetch `https://iodide.io/dist/iodide.pyodide-20180623.css` the server redirect it to `https://iodide-project.github.io/dist/`.

To see these errors, go to here: http://static.imjoy.io/pyodide/python.html and open the chrome dev console. These pyodide files were fetched from the pyodide release v0.8.0, and I simply copy them to https://github.com/oeway/static.imjoy.io/tree/master/docs/pyodide

**Comment by mdboom** [comment] 2019-02-24 22:53
Yes, the connection from the demo notebooks in Pyodide to old versions of Iodide is currently broken.  This will be resolved as we develop a new way to create content in an Iodide notebook that works with current versions.

**Comment by rth** [comment] 2020-05-08 20:42
https://alpha.iodide.io/notebooks/300/ and https://pyodide.cdn.iodide.io/pyodide.js (etc) should work. Closing. Please comment if it's not the case.

**Closed by rth** 2020-05-08 20:42 UTC
Labels: bug
