### ISSUE TITLE
Ship a font for xkcd plots

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#35] opened 2018-05-22 14:03 UTC
matplotlib doesn't include one by default, but expects the user to install one.

If one exists with compatible licensing, we should add it to the build.

**Comment by rth** [comment] 2018-11-05 08:53
Thanks @nixphix ! Would you like to make a Pull Request to add it?

**Comment by nixphix** [comment] 2018-11-05 09:32
Sure will do
________________________________

**Comment by nixphix** [comment] 2018-11-11 09:55
@rth could you give me some pointer on how to add the font asset

**Comment by rth** [comment] 2018-11-11 10:34
I'm not exactly sure. There is a [packages/matplotlib/src/fontList.json](https://github.com/iodide-project/pyodide/blob/8c27b0b44b65bee2374271f12bab794d830d33d1/packages/matplotlib/src/fontList.json) file that lists available fonts available under `/lib/python3.7/site-packages/matplotlib/mpl-data` in the virtual filesystem of the built package. My guess is that the matplolib setup would need to download this additional font and bundle it in somewhere in the filesystem, then one would need to add an entry to `fontList.json`. It's 25 kB font file, and not a frequently used one, so adding it needlessly to the main pyodide package is probably not optimal (though possibly acceptable).

@mdboom would have a better understanding of what needs to be done.

**Comment by rth** [comment] 2018-11-11 10:47
Though the issue is that adding some custom asset is much easier e.g. for the main package (where one can just write the logic in a `Makefile`) than for a packaged python package (which uses the `pyodide_build` setup).

Maybe we could add something similar to the [`build->script` entry in conda's meta.yaml](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#script), that would allow to run arbitrary code. For instance, here we would then use it to run some code to download this asset after patches are applied in matplotlib, but before the install process happens.

**Comment by madhur-tandon** [comment] 2018-12-22 19:11
@mdboom @rth If no one is working on it, can I be assigned this perhaps? Moreover, can I have some starter tips as well?

**Comment by mdboom** [comment] 2018-12-26 18:00
@madhur-tandon: I've assigned you.  @rth's notes above are accurate.  It basically needs to be added to the /lib/python3.7/site-packages/matplotlib/mpl-data directory at the time the package is built, and the `fontList.json` needs to be updated to refer to it.  I think the extra size is reasonable -- it's probably not worth the complexity to have it in, for example, another package.

**Comment by madhur-tandon** [comment] 2019-01-04 21:39
@mdboom @rth Made a PR for adding the font asset. Also, It is better to use the ``post`` entry in my opinion rather than the ``script`` entry in the ``build`` section of the ``meta.yaml`` file. The reasons for this are mentioned in the PR. I have also included a screenshot for the same as a proof that it works. Please let me know if this is feasible. I guess this is straightforward though.

**Closed** 2019-01-07 13:54 UTC
Labels: enhancement, good first issue, matplotlib
