### ISSUE TITLE
working with local package (TypeError: Response has unsupported MIME type)

### ISSUE THREAD

**Issue by mouadhkaabachi** [iodide-project/pyodide#132] opened 2018-08-30 13:08 UTC
I tried to add new package (  [OlaPy](https://pypi.org/project/olapy/) ) using pyodide, after using make all,
I got Build directory that contains all *.js, *.html... files,
when I launched the demo python.html and used   ``` "url": "pyodide.js" ``` , instead of   ```"url": "https://iodide.io/pyodide-demo/pyodide.js" ```, in  ``` %% plugin``` so I can test pyodide with local files, thus, test  (  [OlaPy](https://pypi.org/project/olapy/) ) with pyodide.loadPackage('olapy'), I noticed in my firefox console that even  with "url": "pyodide.js" it still fetching pyodide from https://iodide.io/pyodide-demo/pyodide.js so I changed a ligne in pyodide.js 
```
const baseURL = 'https://iodide.io/pyodide-demo/' 
```
to
``` 
const baseURL = '';
```
and now it load pyodide from my localhost ``` http://localhost:63342/pyodide/build/pyodide.js```
But in the console I got an error TypeError: Response has unsupported MIME type, and ```python plugin downloaded, initializing``` do not pass

**Comment by rth** [comment] 2018-08-31 14:45
On localhost, you may need to serve the files under `build/` with a web-server with [CORS enabled](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
For instance, this [small python script](https://gist.github.com/razor-x/9542707) run from the root of the `pyodide` folder (it runs `cd build` automatically), and loading pyodide from http://localhost:8000/pyodide.js works for me.  Though maybe there is a better way..

**Comment by mouadhkaabachi** [comment] 2018-08-31 16:34
So I changed in pyodide.js  ```const baseURL = 'http://localhost:8000/';``` and start the python script server, and I the same error *Response has unsupported MIME type*
here a screen shot:
https://screenshots.firefox.com/g6PJyFxGlBaM96wK/null
my config:
OS : linux mint 18.3 (kernel 4.15.0)
Browser: Firefox 61.0.1

**Comment by rth** [comment] 2018-08-31 20:58
Thanks for the detailed information. Yes, I can reproduce it after changing the `baseURL`. I think setting,
```py
HTTPRequestHandler.extensions_map['.wasm'] = 'application/wasm'
```
in the above server script, as it is done [here](https://github.com/iodide-project/pyodide/blob/79c97f8d51d839f000283395b4ef829cec241e3b/test/conftest.py#L208) should help (at least it fixes it for me).

**Comment by mouadhkaabachi** [comment] 2018-08-31 21:15
Voila ! it works now, thanks a lot

**Comment by rth** [comment] 2018-09-03 08:14
Great! Feel free to close this issue if it's fixed.

**Closed** 2018-09-03 18:29 UTC

**Comment by rth** [comment] 2018-09-05 17:01
For future reference, using `pyodide_dev.js` instead of `pyodide.js` already includes `const baseURL = '';` which is very practical for loading locally built packages (or those deployed in Circle CI artifacts). Maybe we should document this.

**Comment by mouadhkaabachi** [comment] 2018-09-07 14:59
ah OK, thx for the info :D

**Comment by ceigh** [comment] 2019-02-23 19:21
> Thanks for the detailed information. Yes, I can reproduce it after changing the `baseURL`. I think setting,
> 
> ```python
> HTTPRequestHandler.extensions_map['.wasm'] = 'application/wasm'
> ```
> 
> in the above server script, as it is done [here](https://github.com/iodide-project/pyodide/blob/79c97f8d51d839f000283395b4ef829cec241e3b/test/conftest.py#L208) should help (at least it fixes it for me).

Maybe someone will need this, for Django:

In `settings.py`
```python
import mimetypes

mimetypes.add_type("application/wasm", ".wasm", True)
```
