### ISSUE TITLE
Cannot load Python modules in Safari

### ISSUE THREAD

**Issue by maximpichler** [iodide-project/pyodide#721] opened 2020-07-11 10:15 UTC
With Safari 13.1.1 (15609.2.9.1.2) on macOS 10.15.5 (19F101) Pyodide itself seems to work, but loading any Python module fails with the following error on the console:
```
[Error] Unhandled Promise Rejection: Error: Memory import env:memory provided an 'initial' that is smaller than the module's declared 'initial' import memory size
```

With Chrome and Firefox it works just fine.

This is with a recent revision (018f4a23c9765fc6b0c0b3439d1bea3393924f2e), built via the docker image.

I'm using `pyodide_server.py` from the docs (with port 1234), serving the following page:
```<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript">
        // set the pyodide files URL (packages.json, pyodide.asm.data etc)
        window.languagePluginUrl = 'http://localhost:1234/';
    </script>
    <script src="http://localhost:1234/pyodide.js"></script>
</head>
<body>
  Pyodide test page <br>
  Open your browser console to see pyodide output
  <script type="text/javascript">
        languagePluginLoader.then(function () {
            console.log(pyodide.runPython('import sys\nsys.version'));
            console.log(pyodide.runPython('print(1 + 2)'));
            pyodide.loadPackage('regex').then(() => {
                console.log("regex loaded!");
            });
        });
  </script>
</body>
```

Full console output:
```
[Log] Python initialization complete (pyodide.asm.js, line 8)
[Log] 3.8.2 (default, Jul  9 2020, 20:43:04)  (localhost, line 15)
[Clang 6.0.1 ]
[Log] 3 (pyodide.asm.js, line 8)
[Log] undefined (localhost, line 16)
[Log] regex to be loaded from default channel (pyodide.js, line 146)
[Log] Loading regex (pyodide.js, line 104)
[Log] Loading regex from http://localhost:1234/regex.js (pyodide.js, line 104)
[Error] Unhandled Promise Rejection: Error: Memory import env:memory provided an 'initial' that is smaller than the module's declared 'initial' import memory size
	(anonymous function)
	promiseReactionJob
```

This is after emptying the browser cache. The Safari web inspector shows that all files have been downloaded from localhost (as expected).

**Comment by rth** [comment] 2020-07-11 10:57
Thanks for the detailed report @maximpichler! We don't officially support Safari yet or test it in the CI but fixing this would certainly be useful (cf https://github.com/iodide-project/pyodide/issues/524#issuecomment-542341324).

I'm a bit out of ideas as to what could the the cause of this issue. Searching for Safari related issues at https://github.com/emscripten-core/emscripten/issues could help, though after a quick glance I don't think anyone run into specifically this issue there either.

**Comment by maximpichler** [comment] 2020-07-11 12:02
Ok, I'll try to have a look, although I'm new to most of this.

If any experiment comes to mind and someone doesn't have access to Safari, I'd be happy to run it.

**Comment by mikaelho** [comment] 2020-08-16 07:38
Maybe a dated comment, but does pyodide depend on the availability of [instantiateStreaming](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming)?

**Comment by rth** [comment] 2020-08-16 08:19
> does pyodide depend on the availability of instantiateStreaming?

@mikaelho Good point, but as far as I can tell neither pyodide nor emscripten 1.38.31 uses it. Support for it was added in  emscripten 1.39.6 (https://github.com/emscripten-core/emscripten/pull/10087) but still with explicit checks to exclude Safari.

**Comment by Yharooer** [comment] 2020-09-10 21:51
I get the same error. Can confirm this happens when executing `import numpy`. This does not occur with all python modules, I can still `import micropip` or `import setuptools` on Safari.

**Comment by drscotthawley** [comment] 2020-12-02 01:33
Note that lack of Safari support prevents the use of iOS devices to view content generated by Pyodide.  https://github.com/iodide-project/pyodide/issues/533

**Comment by rth** [comment] 2020-12-03 19:01
> Note that lack of Safari support prevents the use of iOS devices

By "not supported" I meant that it's not currently part of CI. We would be happy to accept fixes for iOS devices. 

As far as I can tell that error is raised on this line of webkit https://github.com/WebKit/webkit/blob/817c46e152af795d735678386db68805d0aa505e/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.cpp#L260. Someone would need to to investigate the cause of it though.

**Comment by rth** [comment] 2020-12-10 20:06
I confirm, I can now reproduce this error when importing regex and numpy in [Midori](https://astian.org/en/midori-browser/) (another Webkit based browser) on Linux with the latest dev version. Loading the core pyodide itself seems to work fine.

**Comment by rth** [comment] 2021-01-21 09:52
The issue is very likely due to the [small `TOTAL_MEMORY` we use](https://github.com/iodide-project/pyodide/blob/f9f01be97da127e03168768ecf24fa6a7eac519b/Makefile#L25). As far as I can tell it used to work with a value of 1GB and now fails with 10MB. There is probably some middle ground we could consider, to that at least most common packages with C extensions (numpy, pandas) would work.

If someone is interested in experimenting with it it would be very helpful.

**Comment by 124bit** [comment] 2021-03-11 08:59
At IOs device with 2 GB ram numpy import failed (0.16.1). I can't look at the js console too. So I don't know the reason. 
However, the import of pure Python modules with micropip works.

Maybe I'll check on a newer device with more ram

**Comment by rth** [comment] 2021-03-11 21:55
> At IOs device with 2 GB ram NumPy import failed (0.16.1)

@124bit  Could you try in the dev console for the latest version on master? https://pyodide-cdn2.iodide.io/dev/full/console.html

I can no longer reproduce this issue with iOS with Safari 14 on a device that has 3GB RAM. Importing numpy, scipy and scikit-learn worked fine for me.

**Comment by 124bit** [comment] 2021-03-11 22:34
At Ipad with 2 gb ram (latest ios 14) the page that you send shows just white screen =(.
My previous comment was based on my simple custom webage with pyiodide from your cdn.

**Comment by drscotthawley** [comment] 2021-03-11 22:38
@rth I confirm @124bit's bare white screen, for iOS 14.4 (Safari) with iPad (with 9.69 GB RAM available), and on MacOS 10.15.7 (Safari 13.1.3 and Brave Version "1.20.108 Chromium: 88.0.4324.182 (Official Build) (x86_64)") on a Late-2016 Macbook Pro.

**Comment by drscotthawley** [comment] 2021-03-11 22:39
Console on MacOS Safari shows 
```
Python initialization complete
pyodide.asm.js:9 Assertion failed: undefined
abort @ pyodide.asm.js:9
assert @ pyodide.asm.js:9
read @ pyodide.asm.js:9
read @ pyodide.asm.js:9
doReadv @ pyodide.asm.js:9
_fd_read @ pyodide.asm.js:9
read @ pyodide.asm.wasm:0x64a4df
_Py_read @ pyodide.asm.wasm:0x3136e4
(anonymous) @ pyodide.asm.wasm:0x4461df
__static_3153 @ pyodide.asm.wasm:0x44629d
byn$fpcast-emu$__static_3153 @ pyodide.asm.wasm:0x6ec4e0
__static_687 @ pyodide.asm.wasm:0x216af2
byn$fpcast-emu$__static_687 @ pyodide.asm.wasm:0x6e3a35
__static_3215 @ pyodide.asm.wasm:0x44aaf5
byn$fpcast-emu$__static_3215 @ pyodide.asm.wasm:0x6ec827
__static_241 @ pyodide.asm.wasm:0x1d6a5a
byn$fpcast-emu$__static_241 @ pyodide.asm.wasm:0x6e231f
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x1cf278
_PyObject_CallMethodIdObjArgs @ pyodide.asm.wasm:0x1cf388
PyImport_ImportModuleLevelObject @ pyodide.asm.wasm:0x2e35ef
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b4a2c
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
_PyEval_EvalCodeWithName @ pyodide.asm.wasm:0x2b0c50
PyEval_EvalCode @ pyodide.asm.wasm:0x2afe1e
__static_1150 @ pyodide.asm.wasm:0x2ad791
byn$fpcast-emu$__static_1150 @ pyodide.asm.wasm:0x6e5291
__static_689 @ pyodide.asm.wasm:0x216e30
byn$fpcast-emu$__static_689 @ pyodide.asm.wasm:0x6e3a5b
PyVectorcall_Call @ pyodide.asm.wasm:0x1ccf59
PyCFunction_Call @ pyodide.asm.wasm:0x1ce45c
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b6419
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
_PyEval_EvalCodeWithName @ pyodide.asm.wasm:0x2b0c50
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd856
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5ef1
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x1cf278
_PyObject_CallMethodIdObjArgs @ pyodide.asm.wasm:0x1cf388
PyImport_ImportModuleLevelObject @ pyodide.asm.wasm:0x2e35ef
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b4a2c
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
PyVectorcall_Call @ pyodide.asm.wasm:0x1ccf59
PyObject_Call @ pyodide.asm.wasm:0x1cd014
_pyproxy_apply @ pyodide.asm.wasm:0x1aa61e
apply @ pyodide.asm.js:9
(anonymous) @ pyodide.js:687
async function (async)
(anonymous) @ pyodide.js:661
(anonymous) @ pyodide.js:701
Show 89 more frames
pyodide.asm.js:9 RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
abort @ pyodide.asm.js:9
_fd_read @ pyodide.asm.js:9
read @ pyodide.asm.wasm:0x64a4df
_Py_read @ pyodide.asm.wasm:0x3136e4
(anonymous) @ pyodide.asm.wasm:0x4461df
__static_3153 @ pyodide.asm.wasm:0x44629d
byn$fpcast-emu$__static_3153 @ pyodide.asm.wasm:0x6ec4e0
__static_687 @ pyodide.asm.wasm:0x216af2
byn$fpcast-emu$__static_687 @ pyodide.asm.wasm:0x6e3a35
__static_3215 @ pyodide.asm.wasm:0x44aaf5
byn$fpcast-emu$__static_3215 @ pyodide.asm.wasm:0x6ec827
__static_241 @ pyodide.asm.wasm:0x1d6a5a
byn$fpcast-emu$__static_241 @ pyodide.asm.wasm:0x6e231f
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x1cf278
_PyObject_CallMethodIdObjArgs @ pyodide.asm.wasm:0x1cf388
PyImport_ImportModuleLevelObject @ pyodide.asm.wasm:0x2e35ef
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b4a2c
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
_PyEval_EvalCodeWithName @ pyodide.asm.wasm:0x2b0c50
PyEval_EvalCode @ pyodide.asm.wasm:0x2afe1e
__static_1150 @ pyodide.asm.wasm:0x2ad791
byn$fpcast-emu$__static_1150 @ pyodide.asm.wasm:0x6e5291
__static_689 @ pyodide.asm.wasm:0x216e30
byn$fpcast-emu$__static_689 @ pyodide.asm.wasm:0x6e3a5b
PyVectorcall_Call @ pyodide.asm.wasm:0x1ccf59
PyCFunction_Call @ pyodide.asm.wasm:0x1ce45c
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b6419
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
_PyEval_EvalCodeWithName @ pyodide.asm.wasm:0x2b0c50
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd856
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5ef1
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f11
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x2b8e17
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b5f6e
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
(anonymous) @ pyodide.asm.wasm:0x1cf278
_PyObject_CallMethodIdObjArgs @ pyodide.asm.wasm:0x1cf388
PyImport_ImportModuleLevelObject @ pyodide.asm.wasm:0x2e35ef
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2b4a2c
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x6cbe75
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2b0e8e
(anonymous) @ pyodide.asm.wasm:0x1cd6cf
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cd7cb
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x6c9394
PyVectorcall_Call @ pyodide.asm.wasm:0x1ccf59
PyObject_Call @ pyodide.asm.wasm:0x1cd014
_pyproxy_apply @ pyodide.asm.wasm:0x1aa61e
apply @ pyodide.asm.js:9
(anonymous) @ pyodide.js:687
async function (async)
(anonymous) @ pyodide.js:661
(anonymous) @ pyodide.js:701
Show 85 more frames
pyodide.js:391 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.globalThis.languagePluginLoader.Module.fatal_error (pyodide.js:391)
    at Object.apply (pyodide.asm.js:9)
    at pyodide.js:687
```

**Comment by rth** [comment] 2021-03-11 23:23
OK, so I tried a bunch of browsers/devices with Safari on browserstack.com

Worked (including numpy)
 - IPad, iOS, v14 
 - IPhone iOS,  v14

Didn't work (and indeed shows a white page)
 - IPad iOS, v13
 - IPhone iOS, v12
 - IPhone iOS, v11

I'm not sure if the Safari version is the only relevant parameter. 2 GB RAM should be enough. As far as I can tell Safari <=v13 doesn't work. v14 does seem to work for me at least on 3 different devices.

Could you re-try a bit later on iOS or MacOS with Safari v14? Because the dev version is re-deployed on each commit on master, maybe we were unlucky with the timing.

> on MacOS 10.15.7 (Safari 13.1.3 and Brave Version "1.20.108 Chromium:

The fact that it also didn't work in a Chrome based browser is suspicious, it could be worth re-trying.

**Comment by rth** [comment] 2021-03-11 23:41
Though MacOS Catalina with Safari v13.1.2 also appeared to work (including for numpy). 

BTW it looks like pyodide got unlimited free credits from browserstack.com for a few months.  The ability to run live an arbitrary combination of a browser, version, OS and device is pretty nice. @pyodide/core let me know if you are interested in getting access to it.  Maybe for testing things around https://github.com/iodide-project/pyodide/pull/1306 by @hoodmane

**Comment by 124bit** [comment] 2021-03-11 23:54
Oh my God!! It works for me now!!!

**Comment by rth** [comment] 2021-03-13 10:53
Thanks for the confirmation. I'm going to close this in #1332 but please comment if you still encounter issues.

**Closed** 2021-03-17 09:05 UTC
Labels: Safari
