### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#423] opened 2019-05-12 21:04 UTC
In the Python console. 

from js import pyodide
pyodide

It generates a nice visual of the object. 
click on the little arrow to see the details, and it generates an error. 

This is on the production server.

**Comment by mdboom** [comment] 2019-05-13 15:35
I think this is a dupe of https://github.com/iodide-project/iodide/issues/1488.

**Closed by mdboom** 2019-05-13 15:35 UTC
